### ISSUE TITLE
Document required labels, and document how to apply labels

### ISSUE THREAD

**Issue by MattSGS** [resin-io/resin-wifi-connect#239]
The wifi connect container wants to talk to the host's dbus, which requires it to have the host's directory containing the host's dbus socket bind-mounted into the wifi connect container.

There's a vague and incomplete description of how to accomplish this using docker-compose metadata labels [here](https://docs.resin.io/learn/develop/multicontainer/#labels).

This documentation should be expanded to describe how to apply these labels. Balena doesn't understand the usual docker compose syntax whereby 'build' is a dictionary, so it's important to document the syntax that balena does accept.

wifi connect's requirement for a 'io.resin.features.dbus' label should be documented in the wifi connect documentation.

Once the resin.io documentation describes how to apply labels, it should be linked to from the wifi connect documentation that describes which label(s) are required.

This example seems to partially work for me (it fails, but for reasons that I suspect are unrelated to this issue):

```
  wifi-connect:
    build: ./wifi-connect
    labels:
      io.resin.features.dbus: '1'
    privileged: true
    environment:
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
      - WIFI_CONNECT_IFACE=wlan0
```
